version: 0.1
os: linux

hooks:
  ApplicationStop:
    - location: scripts/shutdown.sh
      runas: root
  ApplicationStart:
    - location: scripts/startup.sh
      runas: root
  ValidateService:
    - location: scripts/validate.sh
      runas: root
