version: 0.2
env:
    variables:
        CACHE_CONTROL: "86400"
        BUILD_ENV: "prod"
phases:
    install:
        commands:
            - echo Installing source NPM dependencies...
            - npm install --force
            - npm install @angular/cli@13.0.4i
    build:
        commands:
            - echo Build started on `date`
            - ng build --${BUILD_ENV}

artifacts:
    files:
        - '**/*'
    base-directory: 'dist*'
    discard-paths: yes
