version: 0.2

phases:
    install:
        commands:
            - echo Installing source NPM dependencies...
            - echo npm version is $(npm -v)
            - npm install -g @angular/cli@14.0.0 --force
            - npm install --force
            
    build:
        commands:
            - echo Build started on `date`
            - ng build
            - cp appspec.yml dist/appspec.yml
            - cp scripts/startup.sh dist/scripts/startup.sh

artifacts:
    files:
        - '**/*'
    base-directory: 'dist*'
    discard-paths: no
