version: 0.2

phases:
    install:
        commands:
            - echo Installing source NPM dependencies...
            - echo npm version is $(npm -v)
            - npm install -g @angular/cli@13.0.4 --force
            - npm install --force
            
    build:
        commands:
            - echo Build started on `date`
            - echo First showing output of ng update
            - ng update --from 13.0.4 --to 14.0.0
            - ng build

artifacts:
    files:
        - '**/*'
    base-directory: 'dist*'
    discard-paths: yes
